In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [33]:
!gdown 1uUt7uL-VuF_5cpodYRiriEwhsldeEp3m

Downloading...
From: https://drive.google.com/uc?id=1uUt7uL-VuF_5cpodYRiriEwhsldeEp3m
To: c:\Users\subash\OneDrive\Desktop\Machine Learning Repository\ML-Linear-Logistic\ML Introduction\churn_logistic.csv

  0%|          | 0.00/494k [00:00<?, ?B/s]
100%|██████████| 494k/494k [00:00<00:00, 3.23MB/s]
100%|██████████| 494k/494k [00:00<00:00, 3.23MB/s]

In [34]:
churn = pd.read_csv("churn_logistic.csv")
df = churn.copy()
df.head()

,Account Length,VMail Message,Day Mins,Eve Mins,Night Mins,Intl Mins,CustServ Calls,Intl Plan,VMail Plan,Day Calls,...,Eve Calls,Eve Charge,Night Calls,Night Charge,Intl Calls,Intl Charge,State,Area Code,Phone,Churn
0,128,25,265.1,197.4,244.7,10.0,1,0,1,110,...,99,16.78,91,11.01,3,2.70,KS,415,382-4657,0
1,107,26,161.6,195.5,254.4,13.7,1,0,1,123,...,103,16.62,103,11.45,3,3.70,OH,415,371-7191,0
2,137,0,243.4,121.2,162.6,12.2,0,0,0,114,...,110,10.30,104,7.32,5,3.29,NJ,415,358-1921,0
3,84,0,299.4,61.9,196.9,6.6,2,1,0,71,...,88,5.26,89,8.86,7,1.78,OH,408,375-9999,0
4,75,0,166.7,148.3,186.9,10.1,3,1,0,113,...,122,12.61,121,8.41,3,2.73,OK,415,330-6626,0

In [35]:
df.isnull().sum()

Account Length    0
VMail Message     0
Day Mins          0
Eve Mins          0
Night Mins        0
Intl Mins         0
CustServ Calls    0
Intl Plan         0
VMail Plan        0
Day Calls         0
Day Charge        0
Eve Calls         0
Eve Charge        0
Night Calls       0
Night Charge      0
Intl Calls        0
Intl Charge       0
State             0
Area Code         0
Phone             0
Churn             0
dtype: int64

There are no missing values in the dataset

In [36]:
df.dtypes

Account Length      int64
VMail Message       int64
Day Mins          float64
Eve Mins          float64
Night Mins        float64
Intl Mins         float64
CustServ Calls      int64
Intl Plan           int64
VMail Plan          int64
Day Calls           int64
Day Charge        float64
Eve Calls           int64
Eve Charge        float64
Night Calls         int64
Night Charge      float64
Intl Calls          int64
Intl Charge       float64
State              object
Area Code           int64
Phone              object
Churn               int64
dtype: object

Removing Phone column since its not relevant

In [38]:
df.drop("Phone", axis = 1)

,Account Length,VMail Message,Day Mins,Eve Mins,Night Mins,Intl Mins,CustServ Calls,Intl Plan,VMail Plan,Day Calls,Day Charge,Eve Calls,Eve Charge,Night Calls,Night Charge,Intl Calls,Intl Charge,State,Area Code,Churn
0,128,25,265.1,197.4,244.7,10.0,1,0,1,110,45.07,99,16.78,91,11.01,3,2.70,KS,415,0
1,107,26,161.6,195.5,254.4,13.7,1,0,1,123,27.47,103,16.62,103,11.45,3,3.70,OH,415,0
2,137,0,243.4,121.2,162.6,12.2,0,0,0,114,41.38,110,10.30,104,7.32,5,3.29,NJ,415,0
3,84,0,299.4,61.9,196.9,6.6,2,1,0,71,50.90,88,5.26,89,8.86,7,1.78,OH,408,0
4,75,0,166.7,148.3,186.9,10.1,3,1,0,113,28.34,122,12.61,121,8.41,3,2.73,OK,415,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5695,224,0,171.5,160.0,212.4,5.0,1,1,0,99,29.16,103,13.60,102,9.56,2,1.35,DE,510,1
5696,131,0,131.6,179.3,251.2,15.5,1,0,0,95,22.37,109,15.24,129,11.30,3,4.19,MS,415,1
5697,132,0,291.2,234.2,191.7,8.9,1,0,0,104,49.50,132,19.91,87,8.63,3,2.40,MI,408,1
5698,100,0,113.3,197.9,284.5,11.7,4,0,0,96,19.26,89,16.82,93,12.80,2,3.16,MT,415,1
5699,147,0,274.0,231.8,283.6,6.2,0,0,0,92,46.58,82,19.70,83,12.76,1,1.67,MD,408,1

In [43]:
df['Churn'].value_counts()

Churn
0    2850
1    2850
Name: count, dtype: int64

Churn column looks balance, so there is no need for resamplling techinques.